name: Hola mundo Action GH

on:
    push:
        branches:
            - main

jobs:
    hola_mundo:
            name: Imprimir Hola mundo
            runs-on: ubuntu-latest
            steps:
                - name: Revisar el repo
                  uses: actions/checkout@v2

                - name: Ejecutar codigo de python
                  uses: python3 app.py