name: Hola mundo Action GH

on:
    push:
        branches:
            - main

jobs:
    hola_mundo:
            name: Imprimir Hola mundo
            runs-on: ubuntu-latest

            steps:
                - name: Imprimir Hola mundo
                run: echo "Hola muundo"
