name: Hola mundo Action GH

on:
    push:
        branches:
            - main

jobs:
    hola_mundo:
            name: Imprimir Hola mundo
            runs-on: self-hosted
            steps:
                - name: Revisar el repo
                  uses: actions/checkout@v2

                - name: install libs
                  run: pip install -r requeriments.txt

                - name: update
                  run: choco install python

                - name: Ejecutar codigo de python
                  run: python3 app.py